---
- name: Enforce ssh key auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^#PermitRootLogin|^PermitRootLogin
    line: PermitRootLogin prohibit-password
  notify: restart sshd

- name: Disable sshd passwords
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^#PasswordAuthentication|^PasswordAuthentication
    line: PasswordAuthentication no
  notify: restart sshd

- name: Disable sshd pam
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^#UsePAM|^UsePAM
    line: UsePAM no
  notify: restart sshd

- name: Enforce authorized_keys
  ansible.builtin.copy:
    src: authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: "0700"

- name: Configure repos
  ansible.builtin.template:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: "0644"

- name: Install role packages
  ansible.builtin.package:
    name: vim,htop,git,bridge-utils,sudo,ifenslave,chrony

- name: Enable chrony
  ansible.builtin.service:
    name: chrony
    enabled: true
    state: started

- name: Configure dns
  ansible.builtin.template:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: "0644"
