---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: restart sshd

- name: Daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen: daemon-reload
